name: Deploy GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      # Copy semua ke temp_public termasuk key.json
      - name: Prepare public folder
        run: |
          rm -rf temp_public
          mkdir temp_public
          rsync -av ./ temp_public/

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.GH_PAT }}
          publish_dir: ./temp_public
          publish_branch: gh-pages
          keep_files: false
