name: Deploy to GitHub

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Create Deployment
        id: deployment
        uses: actions/create-deployment@v1
        with:
          token: ${{ secrets.GH_PAT }}
          environment: production
          description: "Deploy CloudPlay Panel"
          auto_merge: false
          required_contexts: []

      - name: Prepare public folder
        run: |
          rm -rf temp_public
          mkdir temp_public
          rsync -av --exclude='.git' --exclude='.github' ./ temp_public/

      - name: Deploy Files
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add temp_public
          git commit -m "Deploy via workflow"
          git push origin main

      - name: Mark Deployment as Success
        uses: actions/deployment-status@v1
        with:
          token: ${{ secrets.GH_PAT }}
          deployment_id: ${{ steps.deployment.outputs.deployment_id }}
          state: success
